on: push
name: ðŸš€ Desplegar en pre
jobs:
  deploy_on_pre:
    name: ðŸŽ‰ Deploy on pre
    runs-on: ubuntu-latest
    environment: pre
    steps:
    - name: ðŸšš Get latest code
      uses: actions/checkout@v3
    
    - name: ðŸ“‚ Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWD }}
        server-dir: ${{ secrets.FTP_SERVER_DIR_PRE }}
